name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/latest/download/pandoc-3.1.12.1-linux-amd64.tar.gz
          tar xzf pandoc-3.1.12.1-linux-amd64.tar.gz
          sudo cp pandoc-3.1.12.1/bin/pandoc /usr/local/bin/
          pandoc --version

      - name: Build site
        run: python build.py

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4